add A04 A05 B01
buaatechshare/requirement-investigation pull request #7
Opened 2019-03-12 08:38 UTC by cheng052

2019-03-13 01:22 UTC, naykun commented
#2

2019-03-13 11:32 UTC, RightChris requested changes
### A04查看推荐

参与者只写出未登录用户即可

### A05查看资源

参与者只写出未登录用户即可

相关用例b14举报，还可以看看有没有能补充的

简要描述可以加资源的部分内容预览

### B01修改个人信息

参与者只写出普通用户即可，专家用户继承自普通用户

备选事件流中应加入用户放弃修改的情况

补充约束中用户信息不能包含敏感词汇

2019-03-14 01:58 UTC, cheng052 commented
已按要求修改

2019-03-14 02:54 UTC, RightChris approved these changes

2019-03-14 02:54 UTC, merged